import React from 'react'

class Sitemap extends React.Component {
    static async getInitialProps({ res }) {
        res.setHeader('Content-Type', 'text/xml')
        res.write(`<?xml version="1.0" encoding="utf-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
                <loc>https://sandbox.applitools.com/e-commerce</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/cart</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/contact-us</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/sleek-granite-gloves</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/gorgeous-cotton-computer</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/practical-leather-watch</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/rustic-wool-shirt</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/rustic-iron-plate</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/intelligent-wooden-pants</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/small-paper-gloves</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/small-marble-bottle</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/synergistic-paper-bottle</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/enormous-marble-keyboard</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/fantastic-granite-pants</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/rustic-steel-pants</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/practical-silk-bag</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/aerodynamic-aluminum-clock</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/lightweight-aluminum-shirt</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/ergonomic-leather-bottle</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/lightweight-silk-plate</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/incredible-marble-keyboard</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/practical-plastic-coat</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/products/awesome-bronze-pants</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Games</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Kids</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Health</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Tools</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Outdoors</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Toys</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Music</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Automotive</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Computers</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Books</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Electronics</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Movies</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
            <url>
                <loc>https://sandbox.applitools.com/e-commerce/type/Beauty</loc>
                <lastmod>2023-08-06</lastmod>
                <changefreq>always</changefreq>
                <priority>0.5</priority>
            </url>
        </urlset>`)
        res.end()
    }
}

export default Sitemap;